#!/bin/bash

dir=$(find /root/bash_scripting-1 -type d -name $1)
cd $dir; pwd

## get latest
git pull

## adding files to push
git add .

## use $1 as our message
git commit -m $1

## push files to github
git push -u origin main

# ## testing new lines
